#!/bin/sh

set -e
. "$(dirname "$0")/.common.sh"

test ! -e "$kernel_src/include/uapi/linux/aufs_type.h" || {
  echo "AUFS already included, skipping this script (${0##*/})" >&2
  exit 0
}

: "${kmaj:=$(echo "$KVER" | cut -f1 -d.)}"
: ${aufs_branch:=aufs$(echo $KVER | cut -f1-2 -d.)}
: ${aufs_url:=https://github.com/sfjro/aufs${kmaj}-standalone.git}
: ${aufs_src=$(git_branch=$aufs_branch dl_file $aufs_url)}
for patch in kbuild base mmap standalone;do
( cd "$kernel_src"; patch -p1 ) < "$aufs_src/aufs${kmaj}-${patch}.patch"
done

( cd "$aufs_src"; cp --parents -avt "$kernel_src" Documentation fs include/uapi/linux/aufs_type.h )
